chore(page header): update styles
chanzuckerberg/edu-design-system pull request #1186
Opened 2022-07-08 19:16 UTC by csnizik

### Summary:
https://us02web.zoom.us/j/81533155132?pwd=Z1FpYXlZa3VuSHpUMUI3UmI1NWw5dz09

- Project Overview: replaced <Heading> with <PageHeader> to use kicker and description props
- PageHeader: added optional `as` prop

### Test Plan:

- yarn types runs
- yarn test runs
- yarn lint runs without errors
- yarn start runs

2022-07-11 21:01 UTC, ifrost1 requested changes
Looks good overall. Just a few changes mentioned:
- Description shouldn't have any typography or color styles. The `Text` component can handle those
- Removing commented out code in Section
- Adding size and heading tag names as options for section title

2022-07-11 23:22 UTC, csnizik commented on src/components/Section/Section.module.css
> +  @mixin eds-typography-preset-009;
Done. I moved the text styling to inline styles in the story

2022-07-11 23:23 UTC, csnizik commented on src/components/Section/Section.stories.tsx
> +      <ButtonGroup>
Done

2022-07-11 23:45 UTC, csnizik commented on src/components/Section/Section.tsx
> +            <h2 className={styles['section__title']}>
Done. I had to give the `headingAs` prop a default value since it's a required prop on `<Heading>`

2022-07-11 23:46 UTC, csnizik commented on src/components/Section/Section.tsx
> +        {/* <header className={styles['section__header']}>
Done

2022-07-18 15:45 UTC, dierat commented on .storybook/pages/ProjectOverview/ProjectOverview.tsx
> +                as="p"
Isn't "p" the default `as` for `Text`?

2022-07-18 15:46 UTC, dierat commented on .storybook/pages/ProjectOverview/ProjectOverview.tsx
> +              <p>
I don't think you need this wrapper `p`.

2022-07-18 15:53 UTC, dierat commented on src/components/Section/Section.module.css
> -    # SECTION
This indentation is intentional; all the css file comments have this.

2022-07-18 15:56 UTC, dierat commented
Is the icon here being vertically off-center intentional? It's usually centered.
<img width="650" alt="Screen Shot 2022-07-18 at 8 55 55 AM" src="https://user-images.githubusercontent.com/7761701/179552352-ef2f6ef0-8944-49ca-b408-f3bfb0bf2661.png">

2022-07-19 21:23 UTC, ifrost1 requested changes

2022-07-19 21:23 UTC, ifrost1 commented on src/components/PageHeader/PageHeader.tsx
>          {kicker && <p className={styles['page-header__kicker']}>{kicker}</p>}
Let's use the `Text` component here and point it to the `overline` size.

2022-07-19 21:23 UTC, ifrost1 commented on src/components/PageHeader/PageHeader.tsx
>          {kicker && <p className={styles['page-header__kicker']}>{kicker}</p>}
Wondering if this should be a more generic slot with this to put badges and stuff in there

2022-07-19 21:23 UTC, ifrost1 commented on src/components/PageHeader/PageHeader.tsx
> -          as="h1"
We always want this to be an `h1` tag

2022-07-19 21:23 UTC, ifrost1 commented on src/components/Section/Section.module.css
> +.section__kicker {
Let's apply `eds-size-1` here for 8px spacing between this and the section title

2022-07-19 21:23 UTC, ifrost1 commented on src/components/PageHeader/PageHeader.module.css
> +  @mixin eds-typography-preset-009;
We don't want to use tier 1 presets in components. Let's not bake in a page header kicker and let the `Text` component do the heavy lifting with the styling. This should just be a slot with maybe default spacing underneath

2022-07-19 21:23 UTC, ifrost1 commented on src/components/PageHeader/PageHeader.module.css
> +  @mixin eds-typography-preset-009;
Let's not use tier 1 presets for page header descriptions. Let's also let `Text` do the heavy lifting here.

2022-07-21 23:46 UTC, ifrost1 approved these changes

2022-07-22 13:45 UTC, merged